## Econometric Measures of Connectedness and Risk in Financial Markets
### The model 
- Let $1 + R_t = \frac{P_t}{P_{t-1}}$ be the percentage return for asset i between times t-1 and t.   We define log return as $r_t = log(1 + R_t)$
- Volatility $\sigma_t^2 = Var(r_t^2 | F_{t-1}) = E[(r_t -  \mu_t)^2 | F_{t-1}]$
- Assumes Garch(1,1) model for volatility of asset returns.  
- More specifically, for log returns $r_t$, let $a_t = r_t - \mu_t$ be innovation at time t.  Then $a_t$ ~ Garch(1,1) if:
    
$a_t = \sigma_t \epsilon_t$  

$\sigma_t^2 = \omega_0 + \gamma_1 a_{t-1} + \beta_1 \sigma_{t-1}^2$

where $\epsilon_t$ is the error process, $\epsilon_t$ ~ iid $N(0,1)$ and $(\gamma_1 + \beta_1) < 1$  
### Note
- The constraint is needed to ensure the variance process is finite

### QuasiMaximum Likelihood Estimation
- In order to estimate the parameters of the model, we are going to be maximizing the loglikelihood of the innovation series.  
- Let $\theta = (\omega_0, \gamma_1, \beta_1)$ be the parameter we are trying to estimate
- Let $L(\theta | a_t, a_{t-1}, ..., a_0) = f(a_t, a_{t-1}, ..., a_0 | \theta)$ be the likelihood function which is the joint density of interest 
- To derive the joint density, we use the law of total probability;
  - $f(a_t, a_{t-1}, ..., a_0 | \theta) = f(a_t | F_{t-1})f(a_{t-1} | F_{t-2}) ...f(a_1 | F_0)f(a_o | \theta) = f(a_o | \theta)\prod_{k=1}^t f(a_k | F_{k-1})$

    So...

    $L(\theta | a_t, a_{t-1}, ..., a_0) = f(a_o | \theta)\prod_{k=1}^t f(a_k | F_{k-1})$

- __Note__: We are taking the maximum likelihood of past innovation in the series to the present time t

- Taking the log of the likelihood, we obtain the following equation: 
  - $log(L(\theta | a_t, a_{t-1}, ..., a_0)) = \log{f(a_o | \theta)} + \sum_{k=1}^T \log{f(a_k | F_{k-1})}$

- In a large sample size, contribution from $\log{f(a_o | \theta)}$ is small and hence dropped
- Since $\epsilon_t$ ~ $N(0,1)$, then $a_t$ ~ $N(0, \sigma_t^2)= \frac{1}{\sqrt{2\pi\sigma_t^2}}e^{-\frac{a_t^2}{2\sigma^2_t}}$
  
  So 

  $\log{L(\theta | a_t, a_{t-1}, ..., a_0)} = \sum_{k=1}^t-\frac{1}{2}\log{2\pi\sigma_k^2} - \frac{a_k^2}{2\sigma^2_k}$

- Factoring out the above equation, we get...

  - $\log{L(\theta | a_t, a_{t-1}, ..., a_0)} = -(\frac{t}{2}\log{2\pi} + \sum_{k=1}^{t} \frac{1}{2}\log{\sigma_k^2} + \frac{a_k^2}{2\sigma^2_k})$


- Above is same as minimizing -$\log{L(\theta | a_t, a_{t-1}, ..., a_0)}:=QL(\theta)$
- Since the constant has no affect, we drop it, and get the desired Quasi MLE: 

$QL(\theta) = \frac{1}{2}\sum_{k=1}^{t}\log{\sigma_k^2(\theta)} + \frac{a_k^2}{\sigma^2_k(\theta)}$

### Principal Component Analysis
- Authors use pca on a system of returns.  More specificially, let $\sum_{R} = QDQ^T$ represent the spectral decomposition of 
covariance matrix of $R_t$ where each column is given by $R_i(t) = \frac{R_i(t) - \mu_i(t)}{\sigma_i(t)}$
- D is the eigen values of $\sum_R$ and $Q$ is orthogonol eigen vectors
- Matrix of principal components of $\sum_R$ is then a Txp matrix P given by: $P = RQ$
- Since $Q = col(q_k)_{k=1:n}$ then $RQ = col(Rq_k)_{k=1:n} = (Rq_1 | Rq_2 | ... | Rq_n)$ 
  - Hence $Rq_k = \sum_{i=1}^n R_i q_k(i) = p_k$ the kth column of matrix P 
  - Hence kth principal component of $\sum_R$ is defined as kth column of P and given by $p_k = R_1q_k(1) + R_2q_k(2) + ... + R_nq_k(n)$
### Covariance of Principal Component 
- $\sum_p = T^{-1}PP^T = T^{-1}(RQ)^T(RQ) = T^{-1}(Q^TR^TRQ) = Q^T \sum_R Q = Q^T (QDQ^T)Q = D$; A diagonal whose entries are eigen values of $\sum_R$
- Variance of kth principal component is given by $\lambda_k$
- Total variation in R is sum of eigen values of $\sum_R$ which is $trace(\sum_R)$ 
- Proportion of variation explained by kth principal component $\frac{\lambda_k}{tr(\sum_R)}$

### Granger Causality
- To model the directionality of shocks in a system, the authors use a concept called 'Granger Causality' 
- Time series j is said to 'Granger-Cause' time series i if past values of j contain information helps predict i above and beyond the information contained in past values of i alone. 
- Let $R_t^i$ and $R_t^j$ be two (Tx1) time series with 0 mean.  Their linear relationship is represented with the following model: 

$R_t^i = \gamma_0 + \gamma_1R_{t-1}^i + \gamma_2 R_{t-1}^j + \epsilon_t^i$

$R_t^j = \beta_0 + \beta_1R_{t-1}^i + \beta_2 R_{t-1}^j + \epsilon_t^j$

for an observation at time t.  

Collecting the terms in a matrix, we see: 

$Z_t = \theta_0 + \theta_1 Z_{t-1} + \epsilon_t$

where $Z_t = \begin{pmatrix} R_t^i \\ R_t^j\end{pmatrix}$ is a (2T x 1) vector, $\theta_0 = \begin{pmatrix}\gamma_0 \\ \beta_0\end{pmatrix}$ is a (2T x 1) vector, $\theta_1 = \begin{pmatrix} \gamma_1 & \gamma_2 \\
\beta_1 & \beta_2 \end{pmatrix}$ is a (2T x 2T) matrix 


In [1]:
# simulating a bivariate VAR process
from vector_ar.bivar import BiVariateVar

In [2]:
from vector_ar.bivar import BiVariateVar
bivar = BiVariateVar()
x, y = bivar._simulate_var()
bivar.fit(x, y, p=1)

In [10]:
bivar.theta
print("correlation matrix")
np.corrcoef((bivar.residuals[:,0], bivar.residuals[:, 1]))

array([[3.00220432, 0.39220357, 0.30608992],
       [4.83016781, 0.21222938, 0.09957936]])

correlation matrix


array([[1.        , 0.80759851],
       [0.80759851, 1.        ]])

In [6]:
from statsmodels.tsa.api import VAR
data = pd.DataFrame(np.concatenate((x[:, np.newaxis], y[:, np.newaxis]), axis=1))
v = VAR(data)
result = v.fit(1, trend='c')

In [7]:
result.summary()

  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Fri, 14, Aug, 2020
Time:                     23:40:06
--------------------------------------------------------------------
No. of Equations:         2.00000    BIC:                  -0.970110
Nobs:                     999.000    HQIC:                 -0.988379
Log likelihood:          -2329.75    FPE:                   0.368034
AIC:                    -0.999580    Det(Omega_mle):        0.365833
--------------------------------------------------------------------
Results for equation 0
           coefficient       std. error           t-stat            prob
------------------------------------------------------------------------
const         3.109944         0.231703           13.422           0.000
L1.0          0.387471         0.041874            9.253           0.000
L1.1          0.297355         0.051129            5.816           0.000

Results for equation 1

In [36]:
np.corrcoef((var.residuals[:,0], var.residuals[:, 1]))

array([[1.        , 0.79996231],
       [0.79996231, 1.        ]])

In [11]:
chk = v.select_order(trend='c')

In [12]:
chk.summary()

<class 'statsmodels.iolib.table.SimpleTable'>

In [13]:
d = bivar.auto_select(x, y)

In [17]:
d # high agreement

{'min_bic': (1, -0.971484646091933),
 'bic_results': {(0, -0.3718468862128184),
  (1, -0.971484646091933),
  (2, -0.9482981853109385),
  (3, -0.922363405860413),
  (4, -0.8978131227858318),
  (5, -0.8728075628730364)}}

In [1]:
# checking garch model
from garch.garch import Garch

In [12]:
omega = 0.1
gamma = 0.4
beta = 0.2
w = np.random.standard_normal(10000)
a = np.zeros_like(w)
var = np.zeros_like(w)

for t in range(1, 10000):
    var[t] = omega + gamma * a[t-1]**2 + beta * var[t-1]
    a[t] = w[t] * np.sqrt(var[t])

In [13]:
g = Garch(mean=False)
g.fit(a)

Optimization terminated successfully.
         Current function value: -0.296176
         Iterations: 11
         Function evaluations: 65
         Gradient evaluations: 13


In [14]:
g.theta

array([0.0947502 , 0.36569889, 0.22662725])